AccessCorp.GestaoCategoria.Web/Areas/Admin/Controllers/CategoriaController.cs
using AccessCorp.GestaoCategoria.CrossCutting.ComunicacaoApi;
using AccessCorp.GestaoCategoria.CrossCutting.Helps;
using AccessCorp.GestaoCategoria.Model;
using AccessCorp.GestaoCategoria.Web.Areas.Admin.Controllers.Base;
using AccessCorp.GestaoCategoria.Web.EndPoints;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Linq;

namespace AccessCorp.GestaoCategoria.Web.Areas.Admin.Controllers
{
    [RoutePrefix("admin/categoria/")]
    public class CategoriaController : BaseController
    {
        [HttpGet]
        public ActionResult Cadastrar()
        {
            ViewBag.ExibirMensagem = "";

            return View();
        }

        [Route("cadastrar")]
        [HttpPost]
        public async Task<PartialViewResult> Cadastrar(CategoriaViewModel categoria)
        {
            ChamadaApi<object> _chamadaApiCategoria = new ChamadaApi<object>();

            string dataJSon = HelpObjectJSon<CategoriaViewModel>.Serialize(categoria);

            var resposta = await _chamadaApiCategoria.Post(dataJSon, WebApiGestaoCategoria.AdminCadastrarCategoria);

            ViewBag.ExibirMensagem = Mensagem.Exibir(resposta.ToString());

            return PartialView("_Mensagem");
        }

        [Route("lista")]
        [HttpGet]
        public async Task<JsonResult> Lista()
        {
            ChamadaApi<List<CategoriaViewModel>> _chamadaApiCategoria = new ChamadaApi<List<CategoriaViewModel>>();

            var resposta = await _chamadaApiCategoria.Get(WebApiGestaoCategoria.ListaCategoria);

            var lista = (from l in resposta
                         select new
                         {
                             Id = l.Id,
                             Nome = l.Nome,
                             Descricao = l.Descricao,
                             Slug = l.Slug
                         }).ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }
       
        [Route("exluir")]
        [HttpPost]
        public async Task<PartialViewResult> Excluir(CategoriaViewModel categoriaViewModel)
        {
            ChamadaApi<object> _chamadaApiCategoria = new ChamadaApi<object>();

            var resposta = await _chamadaApiCategoria.Delete(categoriaViewModel.Id.ToString(), WebApiGestaoCategoria.ExcluirCategoria);

            ViewBag.ExibirMensagem = Mensagem.Exibir(resposta.ToString());

            return PartialView("_Mensagem");
        }
        
    }
}

AccessCorp.GestaoCategoria.Web/Areas/Admin/Controllers/SubCategoriaController.cs
using AccessCorp.GestaoCategoria.CrossCutting.ComunicacaoApi;
using AccessCorp.GestaoCategoria.CrossCutting.Helps;
using AccessCorp.GestaoCategoria.Model;
using AccessCorp.GestaoCategoria.Web.Areas.Admin.Controllers.Base;
using AccessCorp.GestaoCategoria.Web.EndPoints;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace AccessCorp.GestaoCategoria.Web.Areas.Admin.Controllers
{
    public class SubCategoriaController : BaseController
    {
        private ChamadaApi<SubCategoriaViewModel> _chamadaApiSubCategoria;
        private ChamadaApi<object> _chamadaApiSubCategoria2;
        private ChamadaApi<List<CategoriaViewModel>> _chamadaApiCategoria;
        private ChamadaApi<List<TipoCampoViewModel>> _chamadaApiTipoCampoViewModel;

        public SubCategoriaController()
        {
            _chamadaApiSubCategoria = new ChamadaApi<SubCategoriaViewModel>();
            _chamadaApiCategoria = new ChamadaApi<List<CategoriaViewModel>>();
            _chamadaApiTipoCampoViewModel = new ChamadaApi<List<TipoCampoViewModel>>();
            _chamadaApiSubCategoria2 = new ChamadaApi<object>();
        }

        [HttpGet]
        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public async Task<PartialViewResult> Cadastrar(SubCategoriaViewModel subCategoria)
        {
            string dataJSon = HelpObjectJSon<SubCategoriaViewModel>.Serialize(subCategoria);

            var result = await _chamadaApiSubCategoria2.Post(dataJSon, WebApiGestaoCategoria.AdminCadastrarSubCategoria);
            
            ViewBag.ExibirMensagem = Mensagem.Exibir(result.ToString());

            return PartialView("_Mensagem");
        }

        [HttpGet]
        public async Task<JsonResult> ListaCategoria()
        {
            var resposta = await _chamadaApiCategoria.Get(WebApiGestaoCategoria.ListaCategoria);

            var lista = (from l in resposta
                         select new
                         {
                             Id = l.Id,
                             Nome = l.Nome
                         }).ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public async Task<JsonResult> ListaTipoCampo()
        {
            var resposta = await _chamadaApiTipoCampoViewModel.Get(WebApiGestaoCategoria.ListaTipoCampo);

            var lista = (from l in resposta
                         select new
                         {
                             Id = l.TipoCampoId,
                             Nome = l.Nome
                         }).ToList();

            return Json(lista, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public PartialViewResult CamposAdicionais()
        {
            return PartialView("_CamposAdicionais");
        }
    }
}

AccessCorp.GestaoCategoria.Web/Areas/Admin/Controllers/TipoCampoController.cs
using AccessCorp.GestaoCategoria.CrossCutting.ComunicacaoApi;
using AccessCorp.GestaoCategoria.Model;
using AccessCorp.GestaoCategoria.Web.EndPoints;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AccessCorp.GestaoCategoria.Web.Areas.Admin.Controllers
{
    public class TipoCampoController : Controller
    {
        private ChamadaApi<List<TipoCampoViewModel>> _chamadaApiTipoCampo;

        public TipoCampoController()
        {
            _chamadaApiTipoCampo = new ChamadaApi<List<TipoCampoViewModel>>();
        }

        public async Task<JsonResult> Lista()
        {

            var lista = await _chamadaApiTipoCampo.Get(WebApiGestaoCategoria.ListaTipoCampo);

            return Json(lista);
        }
    }
}

AccessCorp.GestaoCategoria.Web/Controllers/ContaUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AccessCorp.GestaoCategoria.Web.Controllers
{
    public class ContaUsuarioController : Controller
    {
        // GET: ContaUsuario
        public ActionResult Login()
        {
            return View();
        }
    }
}

AccessCorp.GestaoCategoria.Web/Areas/Admin/Views/Shared/_CamposAdicionais.cshtml
<fieldset class="fieldset">
    <legend>Template</legend>
    <div class="form-group">
        <label for="idTextoObrigatorio" class="col-lg-3 control-label">
            Obrigatório
        </label>

        <input type="checkbox" class="form-control" id="idTextoObrigatorio" ng-model="camposViewModel.Obrigatorio" />

    </div>
    <div class="form-group">
        <label for="idTextoObrigatorio" class="col-lg-3 control-label">
            Descrição (Label)
        </label>

        <input type="number" class="form-control" id="idTextoObrigatorio" ng-model="camposViewModel.Ordem" />

    </div>

    <div class="form-group">
        <label for="idTextoOrdem" class="col-lg-3 control-label">
            Tipos de Campos
        </label>

        <select ng-model="camposViewModel.IdTipoCampo"
                ng-options="tipoCampo.Id as tipoCampo.Nome for tipoCampo in ListaTipoCampo" material-select watch>
            <option value="">Selecione</option>
        </select>
    </div>

    <div class="form-group">
        <label for="idTextoObrigatorio" class="col-lg-3 control-label">
            Ordem
        </label>

        <input type="number" class="form-control" id="idTextoObrigatorio" ng-model="camposViewModel.Ordem" />

    </div>
   
    <div class="form-group">
        <a href="#" class="btn btn-primary form-control" ng-click="AddCampoNgModel(camposViewModel)" 
           data-toggle="tooltip" title="Adicionar Campos">Adicionar Campos</a>
    </div>
</fieldset>

AccessCorp.GestaoCategoria.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestão de Categoria</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/scripts/angular.min.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header tamanho-menu">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <ul class="nav navbar-nav">
                    @Html.ActionLink("Home", "Index", "Home", new { area = "Admin" }, new { @class = "navbar-brand active" })
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Categoria
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Cadastrar", "Cadastrar", "Categoria", new { area = "Admin" }, new { @class = "navbar-brand active" })
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            SubCategoria
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Cadastrar", "Cadastrar", "SubCategoria", new { area = "Admin" }, new { @class = "navbar-brand active" })
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Tipos de Campos
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                @Html.ActionLink("Cadastrar", "Cadastrar", "TipoCampo", new { area = "Admin" }, new { @class = "navbar-brand active" })
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li>
                        <a href="@Url.Action("Login","ContaUsuario",new { Area="Admin"})"><span class="glyphicon glyphicon-log-in"></span> Login</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content topo-distancia-menu borda-cinza">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Todos os direitos reservados <a href="https://accesscorp.com.br/">Access Corp</a></p>
        </footer>
    </div>

</body>
</html>